- name: Run chart-releaser
  uses: helm/chart-releaser-action@v1.4.1
  with:
    charts_dir: charts
    config: cr.yaml
    charts_repo_url: https://github.com/IanBuntinxPXL/helm-charts/tree/gh-pages/charts
  env:
    CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
